### ISSUE TITLE
Bug: Removing Saddle traumatizes Moa

### ISSUE THREAD

**Issue by darksonic300** [The-Aether-Team/Protect-Your-Moa#3]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

47.1.105

### Protect Your Moa Version

1.0.0

### Steps to Reproduce

- Step 1. Tame a Moa
- Step 2. Ride the Moa with a saddle
- Step 3. Remove the saddle from the GUI while riding

### What You Expect To Happen

I expect the Moa to behave normally and wonder around as if nothing was happening, or me dismounting the Moa itself.

### What Actually Happened

The Moa's brain completely turns off and stays stuck looking upwards.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
can't reproduce
