### ISSUE TITLE
Bug: Visual Bug With Armors Appearance and Position in Moas

### ISSUE THREAD

**Issue by SimulationOfMario** [The-Aether-Team/Protect-Your-Moa#5]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Design

### Forge Version

47.2.0

### Protect Your Moa Version

1.20.1-1.0.0

### Is This Bug a Conflict With Another Mod?

I don't know, probably very possible

### Client Log

Nothing is shown every time armor is put on the Moa in the log.

### Steps to Reproduce

1. Tame a Moa 
2. Put armor on it

### What You Expect To Happen

The armor put on the Moa should look good.

### What Actually Happened

Visually it looks bad, it looks small and under the body.

### Additional Details

Here you can see my two Moas with the same problem!

![imagen](https://github.com/The-Aether-Team/Protect-Your-Moa/assets/124881638/b55d8bd6-6040-4228-a4d8-2444c36badda)

(I don't use modpack!)

This is the list of mods that I use, (sorry, there is a lot but the most part they probably have nothing to do with it):

  [✔] ACOFI-SkylightModding-1.20.1-1.0
  [✔] additionallanterns-1.1.1a-forge-mc1.20
  [✔] advancementinfo-1.20-fabric0.83.0-1.4
  [✔] AdvancementPlaques-1.20.1-forge-1.5.1
  [✔] aeroblender-1.20.1-1.0.1-neoforge
  [✔] aether_delight_1.0.0_forge_1.20.1
  [✔] aether_emissivity-1.20.1-1.0.0-neoforge
  [✔] aether_enhanced_extinguishing-1.20.1-1.0.0-neoforge
  [✔] aether_protect_your_moa-1.20.1-1.0.0-neoforge
  [✔] aether_treasure_reforging-1.20.1-1.0.0-neoforge
  [✔] aether-1.20.1-1.4.2-neoforge
  [✔] aether-redux-2.0.11-1.20.1-neoforge
  [✘] aether-redux-2.0.15-1.20.1-neoforge.jar (disabled)
  [✔] Alex's Mobs Music Mod 1.20.1
  [✔] alexscaves-1.1.4
  [✔] alexsdelight-1.5
  [✔] alexsmobs-1.22.8
  [✔] AmbientSounds_FORGE_v6.0.1_mc1.20.1
  [✔] amendments-1.20-1.1.31
  [✔] Amplified_Nether_1.20.x_v1.2.5
  [✔] ancient_aether-0.9.7
  [✔] appleskin-forge-mc1.20.1-2.5.1
  [✔] Aquamirae Mod Boss Music Tweaks 1.20.1
  [✔] aquamirae-6.API15
  [✔] ArmorStatues-v8.0.6-1.20.1-Forge
  [✔] ArmorTrimItemFix-forge-1.20.1-1.0.2
  [✔] ascended_quark-1.20.1-1.0.3
  [✔] ash_api-forge-3.0.2+1.20.1
  [✔] AttributeFix-Forge-1.20.1-21.0.4
  [✔] bclib-3.0.14
  [✔] BeaconOverhaul-1.8.4+1.20
  [✔] beautify-1.1.0+fabric-1.20
  [✔] bestylewither-forge-mc1.20-1.6.1
  [✘] BetterAdvancements-1.20.1-0.3.2.162.jar (disabled)
  [✔] betterarcheology-1.1.9-1.20.1
  [✔] better-end-4.0.11
  [✔] betterendcitiesbetterend-1.20.1
  [✔] betterendrod-1.0.0
  [✔] BetterF3-7.0.2-Forge-1.20.1
  [✘] better-nether-9.0.10.jar (disabled)
  [✔] BetterSmithingTable-1.1.0-Forge-1.20
  [✔] betterstats-3.9.3+fabric-1.20.1
  [✔] BetterThirdPerson-Forge-1.20-1.9.0
  [✔] BetterTridents-v8.0.1-1.20.1-Forge
  [✔] BigShot-forge-1.20.1-1.0.1
  [✔] BlockBlocker-forge-1.20.1-1.8.2
  [✔] blossom-blade-1.2
  [✔] blueprint-1.20.1-7.1.0
  [✔] Boids-1.2.2
  [✔] BOMD-Forge-1.20.1-1.1.2
  [✔] Bookshelf-Forge-1.20.1-20.1.10
  [✔] borderless-mining-1.1.8+1.20.1
  [✘] brewinandchewin-3.0.2+1.20.1.jar (disabled)
  [✔] CerbonsAPI-Forge-1.20.1-1.1.0
  [✔] charmofundying-forge-6.5.0+1.20.1
  [✔] cherishedworlds-forge-6.1.6+1.20.1
  [✔] cherry-villages-1.0.3
  [✔] citadel-2.5.4-1.20.1
  [✔] ClearDespawn-forge-1.20.2-1.1.15
  [✔] clickadv-1.20.1-3.8
  [✔] cloth-config-11.1.118-forge
  [✔] Clumps-forge-1.20.1-12.0.0.4
  [✔] CompletionistsIndex-v8.0.0-1.20.1-Forge
  [✔] configured-forge-1.20.1-2.2.3
  [✔] Connector-1.0.0-beta.43+1.20.1
  [✔] ConnectorExtras-1.10.1+1.20.1
  [✔] continuity-3.0.0-beta.4+1.20.1
  [✔] Controlling-forge-1.20.1-12.0.2
  [✔] cratedelight-2024.05.05-1.20.1-forge
  [✔] CreativeCore_FORGE_v2.11.29_mc1.20.1
  [✔] creeperoverhaul-3.0.2-forge
  [✔] cristellib-1.1.5-forge
  [✔] ctov-forge-3.4.3
  [✔] cupboard-1.20.1-2.6
  [✔] curios-forge-5.9.1+1.20.1
  [✘] davespotioneering-fabric-1.20.1-1.jar (disabled)
  [✔] deep_aether-1.20.1-1.0.3
  [✔] deeperdarker-forge-1.20.1-1.2.1
  [✔] DistinguishedPotions-v8.0.2-1.20.1-Forge
  [✔] do_a_barrel_roll-forge-3.5.6+1.20.1
  [✔] dynamic-fps-3.4.3+minecraft-1.20.0-forge
  [✔] EasyAnvils-v8.0.2-1.20.1-Forge
  [✔] EasyMagic-v8.0.1-1.20.1-Forge
  [✔] EasyShulkerBoxes-v8.0.2-1.20.1-Forge
  [✔] ecologics-forge-1.20.1-2.2.0
  [✔] EffectDescriptions-v8.0.2-1.20.1-Forge
  [✔] embeddium-0.3.19+mc1.20.1-all
  [✔] EnchantmentDescriptions-Forge-1.20.1-17.0.15
  [✔] endermanoverhaul-forge-1.20.1-1.0.4
  [✔] endermite-expansion-1.0.0
  [✔] endrem_forge-5.2.3-R-1.20.X
  [✔] entity_texture_features_forge_1.20.1-6.0.1
  [✔] entityculling-forge-1.6.5-mc1.20.1
  [✘] essential_1-3-2-4_forge_1-20-1.jar (disabled)
  [✔] expanded_ecosphere-3.2.4-forge
  [✔] expcounter-1.20.1-0-forge
  [✔] fabric-api-0.92.1+1.11.8+1.20.1
  [✔] fabric-api-0.92.2+1.20.1
  [✔] fabric-language-kotlin-1.10.20+kotlin.1.9.24(1)
  [✔] Fallingleaves-1.20.1-2.1.0
  [✔] FarmersDelight-1.20.1-1.2.4
  [✔] ferritecore-6.0.1-forge
  [✔] Festive_Delight_1.3_Forge_1.20.1
  [✔] florum-sporum-1.0.0+1.20.1
  [✔] formations-1.0.2-forge-mc1.20
  [✔] formationsnether-1.0.4
  [✔] FpsReducer2-forge-1.20-2.5
  [✔] fusion-1.1.1-fabric-mc1.20.1
  [✔] fusion-1.1.1-forge-mc1.20.1
  [✔] Galosphere-1.20.1-1.4.1-Forge
  [✔] galospheretrimming-1.20.1-1.0.0
  [✔] geckolib-forge-1.20.1-4.4.4
  [✔] GeckoLibOculusCompat-Forge-1.0.1
  [✔] glowing-torchflower-mc1.20-rc1-1.0.0
  [✘] guardvillagers-1.20.1-1.6.4.jar (disabled)
  [✔] head_in_the_clouds-1.0.1
  [✔] Highlighter-1.20.1-forge-1.1.9
  [✔] HopoBetterRuinedPortals-[1.20-1.20.2]-1.3.7
  [✔] HopoBetterUnderwaterRuins-[1.20-1.20.2]-1.1.4b
  [✔] Iceberg-1.20.1-forge-1.1.21
  [✔] ImmediatelyFast-Forge-1.2.15+1.20.4
  [✔] immersivesnow-1.20.1-1.3.0
  [✔] ItemsDisplayedForge-v1.2.2-1.20.1
  [✔] Jade-1.20.1-forge-11.9.2
  [✔] JadeAddons-1.20.1-forge-5.2.2
  [✔] jagmkiwis-1.20.1-1.1.1
  [✔] jearchaeology-1.20.1-1.0.3
  [✔] jeed-1.20-2.1.12
  [✔] jei-1.20.1-forge-15.3.0.4
  [✔] JustEnoughAdvancements-1.20.1-5.0.1
  [✔] justenoughbreeding-forge-1.20.x-1.2.1
  [✔] JustEnoughResources-1.20.1-1.4.0.247
  [✔] kotlinforforge-4.10.0-all
  [✔] L_Enders_Cataclysm-1.99.2 -1.20.1
  [✔] lazurite-1.0.4+mc1.20.1
  [✔] LeaveMyBarsAlone-v8.0.0-1.20.1-Forge
  [✔] LibX-1.20.1-5.0.14
  [✔] lionfishapi-1.9
  [✔] lithostitched-forge-1.20.1-1.1.5
  [✔] lost_aether_content-1.20.1-1.2.3
  [✔] make_bubbles_pop-0.2.0-forge-mc1.19.4+
  [✔] mavapi-1.1.4-mc1.20.1
  [✔] mavm-1.2.6-mc1.20.1
  [✔] memoryleakfix-forge-1.17+-1.1.5
  [✔] midnightlib-forge-1.4.2
  [✔] MindfulDarkness-v8.0.3-1.20.1-Forge
  [✔] modelfix-1.15
  [✔] moonlight-1.20-2.11.31-forge
  [✔] moreadvancementsmod-1.3.0-1.20.1
  [✔] MouseTweaks-forge-mc1.20.1-2.25.1
  [✔] Necronomicon-Forge-1.4.2
  [✘] nether_depths-1.0.0.jar (disabled)
  [✔] nether-s-exoticism-1.20.1-1.2.8
  [✔] notenoughanimations-forge-1.7.3-mc1.20.1
  [✔] notenoughcrashes-4.4.7+1.20.1-forge
  [✘] Nullscape_1.20.4_v1.2.4.jar (disabled)
  [✔] obscure_api-15
  [✔] oculus-mc1.20.1-1.7.0
  [✔] OverflowingBars-v8.0.0-1.20.1-Forge
  [✔] panorama_screens-1.0+forge+mc1.20
  [✔] polymorph-forge-0.49.5+1.20.1
  [✔] PresenceFootsteps-1.9.2
  [✔] PuzzlesLib-v8.1.20-1.20.1-Forge
  [✔] quark_delight_1.0.0_forge_1.20.1
  [✔] Quark-4.0-443
  [✔] QuarkOddities-1.20.1
  [✔] refined-advancements-1.0.3d
  [✔] resourcefulconfig-forge-1.20.1-2.1.2
  [✔] resourcefullib-forge-1.20.1-2.1.25
  [✔] ResourcePackOverrides-v8.0.3-1.20.1-Forge
  [✔] rubidium-extra-0.5.4.3+mc1.20.1-build.121
  [✔] screenshot_viewer-1.3.2-forge-mc1.20.1
  [✔] screenshot-to-clipboard-1.0.9-forge
  [✔] Searchables-forge-1.20.1-1.0.3
  [✔] seasonhud-forge-1.20.1-1.7.19
  [✔] SereneSeasons-1.20.1-9.0.0.46
  [✔] Shield_Overhaul-FORGE-MC1.20.1-1.0.3
  [✔] silk-touch-less-enderchest-1.0
  [✔] SimplyHouses-1.1.4-1.20.1-forge
  [✔] skinlayers3d-forge-1.6.5-mc1.20.1
  [✔] sound-physics-remastered-forge-1.20.1-1.4.2
  [✔] Stackable Potions-forge-1.20.1-1.0.0
  [✔] starlight-1.1.2+forge.1cda73c
  [✔] status-effect-bars-1.0.3
  [✔] Stoneworks-v8.0.0-1.20.1-Forge
  [✔] structure_gel-1.20.1-2.16.2
  [✔] sunflowerdelight-1.20.1-1.0.2.1
  [✔] supermartijn642corelib-1.1.17-forge-mc1.20.1
  [✔] supplementaries-1.20-2.8.10
  [✔] suppsquared-1.20-1.1.14
  [✔] TerraBlender-forge-1.20.1-3.0.1.6
  [✔] TF_Lost_Blocks-1.20.1-1.5.0
  [✔] thaumon-forge-2.2.0+1.20.1
  [✔] tlc_forge-1.0.3-R-1.20.X
  [✔] Towns-and-Towers-1.12-Fabric+Forge
  [✔] transparent-forge-8.0.1+1.20.1
  [✔] tru.e-ending-v1.1.0c
  [✔] Twilight Flavors & Delight-2.0.1
  [✔] twilightforest-1.20.1-4.3.2145-universal
  [✔] UniversalBoneMeal-v8.0.1-1.20.1-Forge
  [✔] upgrade_aquatic-1.20.1-6.0.0
  [✔] Uppers-1.0.1
  [✔] visuality-forge-2.0.2
  [✔] VisualWorkbench-v8.0.0-1.20.1-Forge
  [✔] wakes-0.2.4+1.20.1
  [✔] whats-that-slot-forge-1.3.4+1.20.1
  [✔] Xaeros_Minimap_24.2.0_Forge_1.20
  [✔] XaerosWorldMap_1.38.4_Forge_1.20
  [✔] YetAnotherConfigLib-3.4.2+1.20.1-forge
  [✔] YungsApi-1.20-Forge-4.0.5
  [✔] YungsBetterDesertTemples-1.20-Forge-3.0.3
  [✔] YungsBetterDungeons-1.20-Forge-4.0.4
  [✔] YungsBetterEndIsland-1.20-Forge-2.0.6
  [✔] YungsBetterJungleTemples-1.20-Forge-2.0.5
  [✔] YungsBetterMineshafts-1.20-Forge-4.0.4
  [✔] YungsBetterNetherFortresses-1.20-Forge-2.0.6
  [✔] YungsBetterOceanMonuments-1.20-Forge-3.0.4
  [✔] YungsBetterStrongholds-1.20-Forge-4.0.3
  [✔] YungsBetterWitchHuts-1.20-Forge-3.0.3
  [✔] YungsBridges-1.20-Forge-4.0.3
  [✔] YungsExtras-1.20-Forge-4.0.3
  [✔] YungsMenuTweaks-1.20.1-Forge-1.0.2
  [✔] Zeta-1.0-16
  [✔] Zoomify-2.11.2

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [ ] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by OzPayn** [comment]
You have a mod installed that changes the Moa model, I believe it is Aether Redux. The version of Redux you have is outdated, I believe newer versions have added compatibility with Protect Your Moa

**Comment by SimulationOfMario** [comment]
I discovered it before reading this and I was just going to write it, thank you very much, that's why!
