### ISSUE TITLE
Bug:Incompatibility with Aether lost content making Gravitite Moa Armor Inaccessable/Invisible through the creative inventory and JEI

### ISSUE THREAD

**Issue by MarvelMPH** [The-Aether-Team/Protect-Your-Moa#6]
### What Feature Types Apply to This Bug?

Gui

### What Type of Bug Is This?

Compatibility

### Forge Version

NeoForge 47.1.106

### Protect Your Moa Version

NeoForge - 1.20.1-1.0.0

### Is This Bug a Conflict With Another Mod?

Aether: Lost Content v1.2.3, JEI

### Steps to Reproduce

This happens each time the inventory opens
1.open the inventory/jei
2.type Moa
3.See that gravitite moa armor is not present in JEI and the creative inventory

### What You Expect To Happen

All tiers (Leather - Gravitite) present in the Protect your moa mod to be present and acessable in the creative inventory and their information accessable through JEI

### What Actually Happened

Leather to Zanite Moa armor is visible and accessable but gravitite is missing

### Additional Details

Gravitite moa armor is still craftable in survival and accessable through /give commands below are images of the aether armor tab without lost content and then with lost content. I have also posted this issue in the lost content gitlab
![Without lost content](https://github.com/user-attachments/assets/711adc04-1023-40b7-8fef-f70253bddc4c)
![with lost content](https://github.com/user-attachments/assets/1edad9a4-2f4b-4e03-a649-c115e3f1673b)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Will be fixed in 1.21
